name: Build on Windows

on:
    push:
        branches:
            - '*'

jobs:
    get-extension-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.extension-matrix.outputs.matrix }}
        steps:
        - name: Checkout
          uses: actions/checkout@v5
        - name: Get the extension matrix
          id: extension-matrix
          uses: php/php-windows-builder/extension-matrix@v1
          with:
            extension-url: https://github.com/MarcelBolten/php-pango
            php-version-list: '8.5'
            arch-list: 'x64'
            ts-list: 'nts'

    build:
        needs: get-extension-matrix
        strategy:
            fail-fast: false
            matrix: ${{ fromJson(needs.get-extension-matrix.outputs.matrix) }}

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: php -i
              run: php -i

            - name: Restore vcpkg cache
              id: restore-vcpkg-cache
              uses: actions/cache/restore@v4
              with:
                path: |
                  C:\vcpkg\installed
                  C:\vcpkg\buildtrees
                key: vcpkg-${{ matrix.arch }}-${{ matrix.php-version }}-${{ github.ref_name }}
                restore-keys: |
                  vcpkg-${{ matrix.arch }}-${{ matrix.php-version }}-${{ github.ref_name }}
                  vcpkg-${{ matrix.arch }}-${{ matrix.php-version }}-

            - name: Setup vcpkg and install dependencies
              id: build-deps
              shell: pwsh
              run: |
                # Clone vcpkg if not cached
                if (!(Test-Path "C:\vcpkg")) {
                    git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
                }
                cd C:\vcpkg

                # Bootstrap if needed
                if (!(Test-Path ".\vcpkg.exe")) {
                    .\bootstrap-vcpkg.bat
                }

                # Set architecture
                $triplet = "${{ matrix.arch }}-windows-static-md"

                # Custom triplet for x86 and PHP <= 8.3 to use v142 toolset (Visual Studio 2019 vs16/14.29.30133) to match PHP build
                if ("${{ matrix.arch }}" -eq "x86" `
                    -and "${{ matrix.php-version }}" -ne "master" `
                    -and [version]"${{ matrix.php-version }}" -le [version]"8.3" `
                ) {
                  $triplet = "x86-windows-php"

                  $tripletContent = @(
                    "set(VCPKG_TARGET_ARCHITECTURE x86)"
                    "set(VCPKG_CRT_LINKAGE dynamic)"
                    "set(VCPKG_LIBRARY_LINKAGE static)"
                    "set(VCPKG_PLATFORM_TOOLSET v142)"
                  ) -join "`n"

                  New-Item -Path "C:\vcpkg\triplets\community" -Name "$triplet.cmake" -Value $tripletContent -Force
                }

                # Install all required packages
                $packages = @(
                    "cairo:$triplet",
                    "pango:$triplet",
                    "libpng:$triplet",
                    "freetype:$triplet",
                    "fontconfig:$triplet",
                    "pixman:$triplet",
                    "libjpeg-turbo:$triplet",
                    "zlib:$triplet",
                    "bzip2:$triplet",
                    "brotli:$triplet",
                    "expat:$triplet"
                )
                & .\vcpkg install @packages --overlay-ports=${{ github.workspace }}/vcpkg-overlays

                $depsPath = "C:\vcpkg\installed\$triplet"

                # Write-Host "Libraries build:"
                # Get-ChildItem $depsPath -Recurse | ForEach-Object { Write-Host $_.FullName }

                # Export the path so it can be used in the extension build step
                echo "PANGO_DEPS_PATH=$depsPath" >> $env:GITHUB_OUTPUT

            - name: Save vcpkg cache
              if: steps.restore-vcpkg-cache.outputs.cache-hit != 'true'
              uses: actions/cache/save@v4
              with:
                path: |
                  C:\vcpkg\installed
                  C:\vcpkg\buildtrees
                key: vcpkg-${{ matrix.arch }}-${{ matrix.php-version }}-${{ github.ref_name }}

            - name: Install cairo via PIE
              shell: cmd
              run: |
                curl -L -o pie.phar https://github.com/php/pie/releases/download/1.3.8/pie.phar
                php pie.phar install marcelbolten/php-cairo:^2.0.0alpha2
                php --ri cairo

            - name: Build the extension
              uses: php/php-windows-builder/extension@v1
              with:
                php-version: ${{ matrix.php-version }}
                arch: ${{ matrix.arch }}
                ts: ${{ matrix.ts }}
                args: --with-pango=${{ steps.build-deps.outputs.PANGO_DEPS_PATH }}

            - name: "Upload test outputs"
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                name: pango-test-${{ matrix.php-version }}-${{ matrix.arch }}-${{ matrix.ts }}
                path: tests/**/*.log
