name: Build and Test

on:
    push:
        branches:
            - '*'

jobs:
    Build_Test_Coverage:
        strategy:
            fail-fast: false
            matrix:
                # php-version: [8.2, 8.3, 8.4, 8.5]
                php-version: [8.5]
                os: [ubuntu-latest]
                # phpts: [ts, nts]
                phpts: [nts]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Install system dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y --no-install-recommends \
                build-essential autoconf libtool bison re2c pkg-config \
                libssl-dev libxml2-dev libcairo2-dev libpango1.0-dev \
                libjpeg-turbo8-dev valgrind lcov wget ca-certificates gzip \
                fonts-noto-cjk gdb

            # perhaps need to install some fonts but ubuntu loads too many by default in fonts-noto
            # fonts-noto fonts-noto-cjk fonts-noto-color-emoji

            - name: "Set up PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: pie
              env:
                debug: true
                phpts: ${{ matrix.phpts }}

            - name: "Build Cairo dependency with PIE"
              # Todo: use a stable version after it is released not dev-overhaul branch
              run: sudo pie install marcelbolten/php-cairo:dev-overhaul

            - name: "Checkout"
              uses: actions/checkout@v5

            - name: "Build Pango"
              run: |
                phpize
                ./configure --with-php-config=$(which php-config)
                make -j$(nproc)
                sudo make -j$(nproc) install
              env:
                CFLAGS: "-ggdb3"
                PANGO_COVERAGE: yes

            - name: "Show versions"
              run: |
                whoami
                php -v
                php --ri cairo
                PID=$!
                wait $PID
                ps -T -p $PID 2>/dev/null || echo "Process fully exited"
                sleep 5
                ps -T -p $PID 2>/dev/null || echo "All threads cleaned up"
                ulimit -a
                ulimit -c unlimited
                ulimit -a
                cat /proc/sys/kernel/core_pattern
                php -d extension=pango.so --ri pango || true
                echo "Check if any core dumps are present from previous runs:"
                which coredumpctl
                coredumpctl list
                coredumpctl info
                coredumpctl --help
                coredumpctl debug php -A "\
                  -batch \
                  -ex 'set pagination off' \
                  -ex 'bt full' \
                  -ex 'thread apply all bt' \
                  -ex 'info locals' \
                  -ex 'info registers' \
                  -ex 'quit'"

            - name: "Run Tests"
              run: php ./run-tests.php -d extension=pango.so -j$(nproc) -q --show-diff

            - name: "Upload test outputs"
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                name: pango-test-${{ matrix.php-version }}-${{ matrix.phpts }}
                path: tests/**/*.log

            - name: "Create Coverage report"
              if: ${{ matrix.php-version == '8.4' && matrix.phpts == 'nts' && github.ref_name == 'modern_php' }}
              run: chmod +x ./coverage.sh && ./coverage.sh

            - name: "Publish on gh-pages"
              if: ${{ matrix.php-version == '8.4' && matrix.phpts == 'nts' && github.ref_name == 'modern_php' }}
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./coverage_html

            - name: "Upload coverage report artifacts"
              if: ${{ matrix.php-version == '8.4' && matrix.phpts == 'nts' && github.ref_name == 'modern_php' }}
              uses: actions/upload-artifact@v4
              with:
                name: pango-coverage-8.4
                path: coverage_html
