name: Build and Test

on:
    push:
        branches:
            - '*'
    pull_request:

jobs:
    Build_Test_Coverage:
        strategy:
            fail-fast: false
            matrix:
                php-version: [8.2, 8.3, 8.4, 8.5]
                os: [ubuntu-latest]
                phpts: [ts, nts]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Install system dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y --no-install-recommends \
                build-essential autoconf libtool bison re2c pkg-config \
                libssl-dev libxml2-dev libcairo2-dev \
                libjpeg-turbo8-dev valgrind lcov wget ca-certificates gzip \
                fonts-noto-cjk gdb \
                meson ninja \
                libglib2.0-dev \
                libfontconfig1-dev \
                libfreetype6-dev \
                libharfbuzz-dev \
                libthai-dev \
                libxft-dev \
                libxrender-dev \
                libx11-dev

            # perhaps need to install some fonts but ubuntu loads too many by default in fonts-noto
            # fonts-noto fonts-noto-cjk fonts-noto-color-emoji

            - name: Build modified Pango
              run: |
                git clone --depth 1 --branch marcel-1.52.1-join-fc-thread \
                  https://github.com/MarcelBolten/pango.git
                cd pango
                meson setup build \
                  -Dintrospection=enabled \
                  -Dgtk_doc=false \
                  -Dinstalled_tests=false

                meson compile -C build
                meson install -C build

            - name: "Set up PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: pie
                  ini-values: extension=pango.so
              env:
                debug: true
                phpts: ${{ matrix.phpts }}

            - name: "Build Cairo dependency with PIE"
              # Todo: use a stable version after it is released not dev-overhaul branch
              run: sudo pie install marcelbolten/php-cairo:dev-overhaul

            - name: "Checkout"
              uses: actions/checkout@v5

            - name: "Build Pango"
              run: |
                phpize
                ./configure --with-php-config=$(which php-config)
                make -j$(nproc)
                sudo make -j$(nproc) install
              env:
                CFLAGS: "-ggdb3"
                PANGO_COVERAGE: yes

            - name: "Show versions"
              run: |
                php -v
                php --ri cairo
                php --ri pango
              continue-on-error: true

            - name: "Setup fontconfig cache"
              run: |
                mkdir -p ~/.cache/fontconfig
                mkdir -p ~/.fontconfig
                # Set fontconfig cache location
                echo "FONTCONFIG_PATH=/etc/fonts" >> $GITHUB_ENV
                echo "XDG_CACHE_HOME=$HOME/.cache" >> $GITHUB_ENV
                # Build font cache
                fc-cache -fv

            - name: "Run Tests"
              run: |
                php ./run-tests.php -j$(nproc) --repeat 2 -q --show-diff

            - name: "Upload test outputs"
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                name: pango-test-${{ matrix.php-version }}-${{ matrix.phpts }}
                path: tests/**/*.log

            - name: "Create Coverage report"
              if: ${{ matrix.php-version == '8.4' && matrix.phpts == 'nts' && github.ref_name == 'modern_php' }}
              run: chmod +x ./coverage.sh && ./coverage.sh

            - name: "Publish on gh-pages"
              if: ${{ matrix.php-version == '8.4' && matrix.phpts == 'nts' && github.ref_name == 'modern_php' }}
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./coverage_html

            - name: "Upload coverage report artifacts"
              if: ${{ matrix.php-version == '8.4' && matrix.phpts == 'nts' && github.ref_name == 'modern_php' }}
              uses: actions/upload-artifact@v4
              with:
                name: pango-coverage-8.4
                path: coverage_html
